name:                salary-api
version:             0.1.0.0
github:              "githubuser/salary-api"
license:             BSD3
author:              "ottoMuller"
maintainer:          "otto.muller.general@gmail.com"
copyright:           "2022 Lev Sedov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/salary-api#readme>

dependencies:
- base >= 4.7 && < 5
- hasql
- servant-server
- aeson
- warp
- datetime
- text
- time
- bytestring
- http-conduit
- transformers
- case-insensitive
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  salary-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salary-api

tests:
  salary-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - salary-api
